modelapp/models/__init__.py
from models.decorators import requires_login, requires_admin
from models.design import DesignModel
from models.user import UserModel
from models.result import ResultModel

modelapp/models/decorators.py
import functools
from typing import Callable
from flask import session, flash, redirect, url_for, request, current_app


def requires_login(f: Callable) -> Callable:
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        if not session.get('username'):
            flash('You need to be signed in for this page.', 'danger')
            return redirect(url_for('webuser.login_user'))
        return f(*args, **kwargs)

    return decorated_function

def requires_admin(f: Callable) -> Callable:
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        print(current_app.config.get('ADMIN', ''))
        if session.get('username') not in  current_app.config.get('ADMIN', '').split(','):
            flash('You need to be an administrator to access this page.', 'danger')
            return redirect(url_for('webmodels.index'))
        return f(*args, **kwargs)

    return decorated_function

modelapp/models/design.py
from typing import List

from db import db
from sqlalchemy.sql import func



class DesignModel(db.Model):
    __tablename__ = "models"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(512), nullable=False, unique=False)
    objname = db.Column(db.String(2048), nullable=False, unique=False,default=None)

    username = db.Column(db.String, db.ForeignKey("users.username"), nullable=True)
    user = db.relationship("UserModel",back_populates="design")
    
    time_created = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())

    results = db.relationship("ResultModel", lazy="dynamic")

    @classmethod
    def find_by_name(cls, name: str) -> "DesignModel":
        return cls.query.filter_by(name=name).first()

    @classmethod
    def find_by_username(cls, username: str) -> "DesignModel":
        return cls.query.filter_by(username=username)
    
    @classmethod
    def find_by_designname_and_username(cls, dname: str, uname: str) -> "DesignModel":
        return cls.query.filter_by(name=dname,username=uname).first()


    @classmethod
    def find_by_id(cls, id: int) -> "DesignModel":
        return cls.query.filter_by(id=id).first()

    @classmethod
    def find_all(cls) -> List["DesignModel"]:
        return cls.query.all()
    
    @classmethod
    def find_all_by_username(cls,uname: str) -> List["DesignModel"]:
        return cls.query.filter_by(username=uname)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()

modelapp/models/result.py
from typing import List

from db import db
from sqlalchemy.sql import func



class ResultModel(db.Model):
    __tablename__ = "results"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(512), nullable=False, unique=False)
    objname = db.Column(db.String(2048), nullable=False, unique=False,default=None)

    model_id = db.Column(db.Integer, db.ForeignKey("models.id"), nullable=False)
    model = db.relationship("DesignModel")

    time_created = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())

    saved_by = db.Column(db.String, db.ForeignKey("users.username"), nullable=True)
    saved_user = db.relationship("UserModel",back_populates="result")

    @classmethod
    def find_by_name(cls, name: str) -> "ResultModel":
        return cls.query.filter_by(name=name).first()

    @classmethod
    def find_by_id(cls, id: int) -> "ResultModel":
        return cls.query.filter_by(id=id).first()

    @classmethod
    def find_all(cls) -> List["ResultModel"]:
        return cls.query.all()

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()

modelapp/models/user.py
from db import db


class UserModel(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), primary_key=False, nullable=False, unique=True)
    password = db.Column(db.String(2048), nullable=False)
    email = db.Column(db.String(120), nullable=True,default=None)
    design = db.relationship("DesignModel",back_populates="user",lazy="dynamic")
    result = db.relationship("ResultModel",back_populates="saved_user",lazy="dynamic")

    @classmethod
    def find_by_username(cls, username: str) -> "UserModel":
        return cls.query.filter_by(username=username).first()

    @classmethod
    def find_by_id(cls, _id: int) -> "UserModel":
        return cls.query.filter_by(id=_id).first()

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()

modelapp/views/web_designs.py
from flask import Blueprint, request, session, url_for, render_template, redirect,flash,current_app,send_from_directory, jsonify
#from resources.user import  User, UserModel
#from schemas.user import UserSchema
from schemas.design import DesignSchema
from models import requires_login, requires_admin, DesignModel
from werkzeug.security import safe_str_cmp
from flask_uploads import UploadNotAllowed
from libs import image_helper
import os
import datetime
import logging
import traceback
from sqlalchemy import exc

from datetime import  timezone
import calendar

logger = logging.getLogger()
webmodel_blueprint = Blueprint('webmodels', __name__)
design_schema = DesignSchema()
design_list_schema = DesignSchema(many=True)



@webmodel_blueprint.route("/new", methods=["GET", "POST"])
@requires_login
def create_model():
    if request.method == "POST":

        if 'file1' not in request.files:
            return "Missing file part"

        file1 = request.files['file1']
        name = file1.filename
        if DesignModel.find_by_designname_and_username(name,session['username']):
            return "Model already exists with name. Try another name"

        try:
            username = session['username']
            folder = f"user_{username}"
            image_path = image_helper.save_image(file1, folder=os.path.join(folder))
            logger.info(image_path)
            basename = image_helper.get_basename(image_path)
            logger.info(basename)
        except UploadNotAllowed:  # forbidden file type
            extension = image_helper.get_extension(file1)
            return  f"Unable to upload the extension {extension}"

        design = DesignModel(name=name,username=session['username'],objname=image_path)
        try:
            design.save_to_db()
        except:
            traceback.print_exc()
            return "Error creating model"

        return redirect(url_for(".index"))

    return render_template("models/new_model.html")

@webmodel_blueprint.route("/")
@requires_login
def index():
    models = DesignModel.find_by_username(session["username"])
    #print(design_list_schema.dump(models))
    return render_template("models/index.html", models=design_list_schema.dump(models))

@webmodel_blueprint.route("/edit/<string:model_id>", methods=["GET", "POST"])
@requires_login
def edit_model(model_id):
    if request.method == "POST":
        name = request.form['name']
        model = DesignModel.find_by_id(model_id)
        model.name = name
        try:
            model.save_to_db()
        
        except:
            traceback.print_exc()
            flash('Error renaming model', 'danger')
            #return "Error renaming model"

        return redirect(url_for(".index"))
        
    # What happens if it's a GET request
    return render_template("models/edit_model.html", model=DesignModel.find_by_id(model_id))

@webmodel_blueprint.route("/delete/<string:model_id>")
@requires_login
def delete_model(model_id):
    model = DesignModel.find_by_id(model_id)
    if model and model.username == session["username"]:
        
        try:
            model.delete_from_db()
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'])
            os.remove(os.path.join(uploads,model.objname))
        except exc.IntegrityError as e:
            traceback.print_exc()
            flash('Unable to delete the model due to constraint on Results','danger')       
        except:
            traceback.print_exc()
            flash('File deletion failed','danger')
    else:
        flash('Unauthorized: Unable to delete model id {}'.format(model_id), 'danger')

    return redirect(url_for(".index"))


@webmodel_blueprint.route("/download/<string:model_id>")
@requires_login
def download_file(model_id):

    model = DesignModel.find_by_id(model_id)
    if model and (model.username == session["username"] or  session["admin"] == True):
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'], os.path.dirname(model.objname))
            return send_from_directory(directory=uploads, filename=os.path.basename(model.objname),attachment_filename=model.name,as_attachment=True)
        except:
            traceback.print_exc()
            return "File not found!"
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return redirect(url_for(".index",model_id=model_id))

@webmodel_blueprint.route("/display/<string:model_id>",methods=["GET", "POST"])
@requires_login
def display_file(model_id):
    logger.info('model_id=' + model_id)
    model = DesignModel.find_by_id(model_id)
    if model and (model.username == session["username"] or  session["admin"] == True):
        try:
            suffix_list = ['.json', '.txt', '.csv'] 
            suffix_match = model.objname.endswith(tuple(suffix_list))
           
            if suffix_match:
                fname = os.path.join( current_app.config['UPLOADED_FILES_DEST'], model.objname)
                
                with open(fname, 'r') as file:
                     data = file.read()
                return jsonify({'text': data})
            else:
                return jsonify({'Error': 'Unknown file suffix.'})
            
        except:
            traceback.print_exc()
            jsonify({'Error': 'File Not found.'})
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return  jsonify({'text': 'Error'})

@webmodel_blueprint.route("/update/<string:model_id>",methods=["POST"])
@requires_login
def update_file(model_id):
    logger.info('model_id=' + model_id)
    logger.info('text=' + request.form['text'])

    model = DesignModel.find_by_id(model_id)
    utc_dt =  datetime.datetime.utcnow().replace(microsecond=0)
    model.time_created =  utc_dt
    try:
        
        fname = os.path.join( current_app.config['UPLOADED_FILES_DEST'], model.objname)
        out_file = open(fname, "w")
        out_file.writelines(request.form['text'])
        out_file.close()

        model.save_to_db()
    
    except:
        traceback.print_exc()
        flash('Error updating model', 'danger')
        #return "Error renaming model"

    #native = utc_dt.replace(tzinfo=None)
    native = utc_dt.replace(tzinfo=timezone.utc).astimezone(tz=None)
    format='%b %d, %Y %I:%M %p %Z'

    return  jsonify({'status': 'Ok', 'time_updated':'Date/Time: '+native.strftime(format)})

modelapp/views/web_designs_all.py
from flask import Blueprint, request, session, url_for, render_template, redirect,flash,current_app,send_from_directory
#from resources.user import  User, UserModel
#from schemas.user import UserSchema
from schemas.design import DesignSchema
from models import requires_login, requires_admin, DesignModel
from werkzeug.security import safe_str_cmp
from flask_uploads import UploadNotAllowed
from libs import image_helper
import os
import datetime
import logging
import traceback

logger = logging.getLogger()
webmodel_all_blueprint = Blueprint('webmodels_all', __name__)
design_schema = DesignSchema()
design_list_schema = DesignSchema(many=True)


@webmodel_all_blueprint.route("/")
@requires_login
@requires_admin
def index():
    models = DesignModel.find_all()
    return render_template("models/indexall.html", models=design_list_schema.dump(models))

@webmodel_all_blueprint.route("/delete/<string:model_id>")
@requires_login
@requires_admin
def delete_model(model_id):
    model = DesignModel.find_by_id(model_id)
    if model and session["admin"] == True:
        model.delete_from_db()
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'])
            os.remove(os.path.join(uploads,model.objname))
        except:
            traceback.print_exc()
            flash('File deletion failed','danger')
    else:
        flash('Unauthorized: Unable to delete model id {}'.format(model_id), 'danger')

    return redirect(url_for("webmodels_all.index"))


@webmodel_all_blueprint.route("/download/<string:model_id>")
@requires_login
@requires_admin
def download_file(model_id):

    model = DesignModel.find_by_id(model_id)
    if model and session["admin"] == True:
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'], os.path.dirname(model.objname))
            return send_from_directory(directory=uploads, filename=os.path.basename(model.objname),attachment_filename=model.name,as_attachment=True)
        except:
            traceback.print_exc()
            return "File not found!"
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return redirect(url_for("webmodels_all.index",model_id=model_id))

modelapp/views/web_results.py
from flask import Blueprint, request, session, url_for, render_template, redirect,flash,current_app,send_from_directory
#from resources.user import  User, UserModel
#from schemas.user import UserSchema
from schemas.result import ResultSchema
from models import requires_login, requires_admin, DesignModel, ResultModel
from werkzeug.security import safe_str_cmp
from flask_uploads import UploadNotAllowed
from libs import image_helper
import os
import datetime
import logging
import traceback

logger = logging.getLogger()
webresult_blueprint = Blueprint('webresults', __name__)
result_schema = ResultSchema()
result_list_schema = ResultSchema(many=True)


@webresult_blueprint.route("/<string:model_id>")
@requires_login
def index(model_id):
    
    model = DesignModel.find_by_id(model_id)
    if model and (model.username == session["username"] or  session["admin"] == True):
        #print(result_list_schema.dump(model.results))
        return render_template("results/index.html", results=result_list_schema.dump(model.results), model_name=model.name)
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')
        return redirect(url_for("webmodels.index"))

@webresult_blueprint.route("/download/<string:result_id>")
@requires_login
def download_file(result_id):
    result = ResultModel.find_by_id(result_id)
    model = DesignModel.find_by_id(result.model_id)

    if model and (model.username == session["username"] or  session["admin"] == True):
        try:
            #Set custom mimetype and as_attmt values
            custom_mimetypes = {
                '.txt': 'text/plain',
                '.json': 'text/plain',
                '.csv': 'text/plain',
            }
            file_ext = os.path.basename(result.objname)[-4:]
            mimetype = custom_mimetypes.get(file_ext, None)
            #text files will open in new tab
            as_attachment = False if mimetype in ['text/plain'] else True

            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'], os.path.dirname(result.objname))
            return send_from_directory(directory=uploads, 
                                        filename=os.path.basename(result.objname),
                                        attachment_filename=result.name,
                                        mimetype=mimetype,
                                        as_attachment=as_attachment)
        except:
            traceback.print_exc()
            return "File not found!"
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return redirect(url_for(".index",model_id=model.id))

@webresult_blueprint.route("/delete/<string:result_id>")
@requires_login
def delete_result(result_id):
    result = ResultModel.find_by_id(result_id)
    model = DesignModel.find_by_id(result.model_id)
    if result and model and model.username == session["username"]:
        result.delete_from_db()
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'])
            os.remove(os.path.join(uploads,result.objname))
        except:
            traceback.print_exc()
            flash('Result File deletion failed','danger')
    else:
        flash('Unauthorized: Unable to delete result id {}'.format(result_id), 'danger')

    return redirect(url_for(".index",model_id=model.id))

modelapp/templates/models/edit_model.html
{% extends "base.html" %}
{% block content %}
<header class="container">
    <h1>Edit Model</h1>
</header>
<section class="container">
    <form method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ model.name }}" enabled>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</section>
{% endblock %}

modelapp/templates/models/index.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    <header>
        <h1>Models</h1>
    </header>
    <section>

        <form action="{{ url_for('webmodels.create_model') }}" enctype="multipart/form-data" method="post">
            <div class="form-group">
                <div class="form-group">
                    <label for="file1">File</label>
                    <input type="file" name="file1" id="file1" autocomplete="off" required>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
        <br></br>
        <div id="data-list" class="list-group">
            {% for model in models %}
            <div class="list-group-item">

                <dl>
                    <dt>
                        <a class="list-group-item-heading" style="font-size: 150%" aria-describedby="fileHelp{{ model.id }}"
                            href="{{ url_for('webmodels.download_file', model_id=model.id) }}">{{ model.name }}</a>
                            {% if( model.name.endswith('.json') or model.name.endswith('.txt') or model.name.endswith('.csv') )%}
                                <span id="fetch{{ model.id }}">
                                <a href="javascript:display( '#display{{ model.id }}','#detail{{ model.id }}','{{ model.id }}');">
                                    <button id="edit{{ model.id }}" type="button" style="font-size: 1em;"
                                        class="btn btn-secondary btn-sm collapsed toggle fas fa-angle-double-down m-4" data-toggle="collapse"
                                        data-target="#display{{ model.id }}">Expand</button> </a>

                                <div id="display{{ model.id }}" class="collapse mt-2" cshow="off">
                                    <span id="update{{ model.id }}">
                                        <textarea id="detail{{  model.id }}" class="form-control z-depth-1" cols="50"
                                            rows="3" wrap>ext here to edit</textarea>
                                        <a href="javascript:update('#edit{{ model.id }}','#detail{{ model.id }}','#fileHelp{{ model.id }}','{{ model.id }}');">
                                        <button class="btn btn-sm btn-secondary mt-1" type="button">Save</button> </a>
                                    </span>
                                </div>
                            </span>
                        {% endif %}
                    </dt>
                    <dd>
                        <small id="fileHelp{{ model.id }}" class="form-text text-muted">Date/Time:
                            {{ model.time_created |strftime }}</small>
                    </dd>
                    <a class="btn btn-secondary btn-sm mt-0"
                        href="{{ url_for('webresults.index', model_id=model.id) }}">
                        View Results
                    </a>
                    <a class="btn btn-danger btn-sm mt-0"
                        href="{{ url_for('webmodels.delete_model', model_id=model.id) }}">
                        Permanently Delete Model
                    </a>
                </dl>

            </div>
            {% endfor %}
        </div>


    </section>
</div>
{% endblock %}

modelapp/templates/models/indexall.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <header>
        <h1>All Models</h1>
    </header>
    <section>
        <div class="list-group">
            {% for model in models %}
            <div class="list-group-item" >
                
                    <dl>
                        <dt>
                            <a class="list-group-item-heading" style="font-size: 150%" aria-describedby="fileHelp" href="{{ url_for('webmodels.download_file', model_id=model.id) }}">{{ model.name }}</a>
                        </dt>
                        <dd>
                            <small id="fileHelp" class="form-text text-muted">User: {{ model.username }}, Date/Time: {{ model.time_created |strftime }}</small>
                        </dd>
                        <a class="btn btn-danger btn-sm mt-0" href="{{ url_for('webmodels_all.delete_model', model_id=model.id) }}">
                            Permanently Delete Model
                        </a>
                    </dl>

            </div>
            {% endfor %}
        </div>


    </section>
</div>
{% endblock %}

modelapp/templates/models/new_model.html
{% extends "base.html" %}
{% block content %}
<header class="container">
    <h1>Create Model</h1>
</header>
    <section class="container">
        <form action="{{ url_for('webmodels.create_model') }}" enctype="multipart/form-data" method="post">
            <div class="form-group">
                <div class="form-group">
                    <label for="file1">File</label>
                    <input type="file" name="file1" id="file1" autocomplete="off" required >
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </section>

{% endblock %}