modelapp/views/web_results_all.py
from flask import Blueprint, request, session, url_for, render_template, redirect,flash,current_app,send_from_directory
#from resources.user import  User, UserModel
#from schemas.user import UserSchema
from schemas.result import ResultSchema
from models import requires_login, requires_admin, DesignModel, ResultModel
from werkzeug.security import safe_str_cmp
from flask_uploads import UploadNotAllowed
from libs import image_helper
import os
import datetime
import logging
import traceback

logger = logging.getLogger()
webresult_all_blueprint = Blueprint('webresults_all', __name__)
result_schema = ResultSchema()
result_list_schema = ResultSchema(many=True)


@webresult_all_blueprint.route("/")
@requires_login
@requires_admin
def index():
    results = ResultModel.find_all()
    return render_template("results/indexall.html", results=result_list_schema.dump(results))


@webresult_all_blueprint.route("/download/<string:result_id>")
@requires_login
@requires_admin
def download_file(result_id):

    result = ResultModel.find_by_id(result_id)

    model = DesignModel.find_by_id(result.model_id)

    if model and   session["admin"] == True:
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'], os.path.dirname(result.objname))
            return send_from_directory(directory=uploads, filename=os.path.basename(result.objname),attachment_filename=result.name,as_attachment=True)
        except:
            traceback.print_exc()
            return "File not found!"
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return redirect(url_for(".index"))

@webresult_all_blueprint.route("/delete/<string:result_id>")
@requires_login
@requires_admin
def delete_result(result_id):
    result = ResultModel.find_by_id(result_id)
    model = DesignModel.find_by_id(result.model_id)
    if result and model and session["admin"] == True:
        result.delete_from_db()
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'])
            os.remove(os.path.join(uploads,result.objname))
        except:
            traceback.print_exc()
            flash('Result File deletion failed','danger')
    else:
        flash('Unauthorized: Unable to delete result id {}'.format(result_id), 'danger')

    return redirect(url_for(".index"))

modelapp/views/web_user.py
from flask import Blueprint, request, session, url_for, render_template, redirect, current_app
from resources.user import  User, UserModel
from schemas.user import UserSchema
from models import requires_login, DesignModel
from werkzeug.security import safe_str_cmp
from libs.utils import Utils


webuser_blueprint = Blueprint('webuser', __name__)
@webuser_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = UserModel.find_by_username(username)

        try:
            #if user and safe_str_cmp(password, user.password):
            if user and Utils.check_hashed_password(password, user.password):
                session['username'] = user.username
                if user.username in current_app.config.get('ADMIN', '').split(','):
                    session['admin'] = True
                else:
                    session['admin'] = None

                return redirect(url_for("webmodels.index"))
            else:
                session['username'] = None
                session['admin'] = None
                return "Invalid credentials! please try again."
        except:
            session['username'] = None
            session['admin'] = None
            return "Invalid credentials! please try again."

    return render_template("users/login.html")  

@webuser_blueprint.route('/logout', methods=['GET'])
@requires_login
def logut_user():
    session['username'] = None
    session['admin'] = None
    return render_template('home.html')

@webuser_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        #email = request.form['email']

        if UserModel.find_by_username(username):
            return "Username already exists! Try with another name."
        else:
            hashed_password=Utils.hash_password(password)
            user = UserSchema().load({"username":username, "password":hashed_password})
            user.save_to_db()
            session['username'] = user.username
            if user.username in current_app.config.get('ADMIN', '').split(','):
                session['admin'] = True
            else:
                session['admin'] = None

            return redirect(url_for("webmodels.index"))

    return render_template("users/register.html")  

modelapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Model App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <style>label.required:after {content: " *"; color: red;}</style>
</head>

<body>
    <div class="content container mt-2">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
            <a class="navbar-brand" href="#">Model App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav"></div>
                {% if session['username'] %}
                    <a class="nav-item nav-link" href="{{ url_for('webmodels.index') }}">Models</a>
                    {% if session['username']  and session['admin'] %}
                        <a class="nav-item nav-link" href="{{ url_for('webmodels_all.index') }}">All Models</a>
                        <a class="nav-item nav-link" href="{{ url_for('webresults_all.index') }}">All Results</a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{{ url_for('webuser.logut_user') }}">Sign Out</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('webuser.login_user') }}">Log in</a>
                    <a class="nav-item nav-link" href="{{ url_for('webuser.register_user') }}">Sign up</a>
                {% endif %}
                </div>  
                {% if session['username'] %}
                    <div class="navbar-right" ><p class="navbar-text">Welcome {{ session['username'] }}</p></div>
                {% endif %}
            </div>
           
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="container alert alert-{{category}}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <div class="mt-3">
        {% block content %}

        {% endblock %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block moreScripts %}
 
    <script>
        function display( destElem, detailElem, model) {
      
            if($(destElem).attr('cshow') == 'off') {
                $(detailElem).html('<img src="{{ url_for('static', filename='images/loading.gif') }}">');
                $.post('display/'+model, {
                    model_id: model
                }).done(function(response) {
                    
                    $(detailElem).val(response['text']);
                    $(destElem).attr('cshow','on');
                    $('#edit'+model).removeClass('fas')
                    $('#edit'+model).removeClass('fa-angle-double-up')
                    $('#edit'+model).removeClass('fa-angle-double-down')
                    $('#edit'+model).html('<span  class="collapsed toggle fas fa-angle-double-up"></span> Close');


                }).fail(function() {
                    $(destElem).text("Error: Could not contact server.");
                    $(destElem).attr('cshow','on');
                    $('#edit'+model).removeClass('fas')
                    $('#edit'+model).removeClass('fa-angle-double-up')
                    $('#edit'+model).removeClass('fa-angle-double-down')
                    $('#edit'+model).html('<span class="collapsed toggle fas fa-angle-double-up"></span> Close');
                });
        }
        else {
            $(destElem).attr('cshow','off');
            $('#edit'+model).removeClass('fas')
            $('#edit'+model).removeClass('fa-angle-double-up')
            $('#edit'+model).removeClass('fa-angle-double-down')
            $('#edit'+model).html('<span class="collapsed toggle fas fa-angle-double-down"></span> Expand');
        }

        }
    </script>

    <script>
        function update( editElem, detailElem, helpElem, model) {
            $(editElem).click();
            $.post('update/'+model, {
                        model_id: model,
                        text: $(detailElem).val()
                    }).done(function(response) {
                    $(helpElem).text(response['time_updated']);
                        //console.log(response['status']);
                    }).fail(function() {
                        console.info("Error: Could not contact server.");

                    });
        }
    </script>
    {% endblock moreScripts %}

</body>

</html>

modelapp/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron container">
        <h1 class="display-4">Model App</h1>
        <p class="lead">Register your models.</p>
        <hr class="my-4">
        <p>Just sign up, and get started to add models. We'll do the rest!</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('webuser.register_user') }}" role="button">Get started</a></p>
    </div>
{% endblock %}