modelapp/models/result.py
from typing import List

from db import db
from sqlalchemy.sql import func



class ResultModel(db.Model):
    __tablename__ = "results"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(512), nullable=False, unique=False)
    objname = db.Column(db.String(2048), nullable=False, unique=False,default=None)

    model_id = db.Column(db.Integer, db.ForeignKey("models.id"), nullable=False)
    model = db.relationship("DesignModel")

    time_created = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())

    saved_by = db.Column(db.String, db.ForeignKey("users.username"), nullable=True)
    saved_user = db.relationship("UserModel",back_populates="result")

    @classmethod
    def find_by_name(cls, name: str) -> "ResultModel":
        return cls.query.filter_by(name=name).first()

    @classmethod
    def find_by_id(cls, id: int) -> "ResultModel":
        return cls.query.filter_by(id=id).first()

    @classmethod
    def find_all(cls) -> List["ResultModel"]:
        return cls.query.all()

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()

modelapp/views/web_results.py
from flask import Blueprint, request, session, url_for, render_template, redirect,flash,current_app,send_from_directory
#from resources.user import  User, UserModel
#from schemas.user import UserSchema
from schemas.result import ResultSchema
from models import requires_login, requires_admin, DesignModel, ResultModel
from werkzeug.security import safe_str_cmp
from flask_uploads import UploadNotAllowed
from libs import image_helper
import os
import datetime
import logging
import traceback

logger = logging.getLogger()
webresult_blueprint = Blueprint('webresults', __name__)
result_schema = ResultSchema()
result_list_schema = ResultSchema(many=True)


@webresult_blueprint.route("/<string:model_id>")
@requires_login
def index(model_id):
    
    model = DesignModel.find_by_id(model_id)
    if model and (model.username == session["username"] or  session["admin"] == True):
        #print(result_list_schema.dump(model.results))
        return render_template("results/index.html", results=result_list_schema.dump(model.results), model_name=model.name)
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')
        return redirect(url_for("webmodels.index"))

@webresult_blueprint.route("/download/<string:result_id>")
@requires_login
def download_file(result_id):
    result = ResultModel.find_by_id(result_id)
    model = DesignModel.find_by_id(result.model_id)

    if model and (model.username == session["username"] or  session["admin"] == True):
        try:
            #Set custom mimetype and as_attmt values
            custom_mimetypes = {
                '.txt': 'text/plain',
                '.json': 'text/plain',
                '.csv': 'text/plain',
            }
            file_ext = os.path.basename(result.objname)[-4:]
            mimetype = custom_mimetypes.get(file_ext, None)
            #text files will open in new tab
            as_attachment = False if mimetype in ['text/plain'] else True

            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'], os.path.dirname(result.objname))
            return send_from_directory(directory=uploads, 
                                        filename=os.path.basename(result.objname),
                                        attachment_filename=result.name,
                                        mimetype=mimetype,
                                        as_attachment=as_attachment)
        except:
            traceback.print_exc()
            return "File not found!"
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return redirect(url_for(".index",model_id=model.id))

@webresult_blueprint.route("/delete/<string:result_id>")
@requires_login
def delete_result(result_id):
    result = ResultModel.find_by_id(result_id)
    model = DesignModel.find_by_id(result.model_id)
    if result and model and model.username == session["username"]:
        result.delete_from_db()
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'])
            os.remove(os.path.join(uploads,result.objname))
        except:
            traceback.print_exc()
            flash('Result File deletion failed','danger')
    else:
        flash('Unauthorized: Unable to delete result id {}'.format(result_id), 'danger')

    return redirect(url_for(".index",model_id=model.id))

modelapp/views/web_results_all.py
from flask import Blueprint, request, session, url_for, render_template, redirect,flash,current_app,send_from_directory
#from resources.user import  User, UserModel
#from schemas.user import UserSchema
from schemas.result import ResultSchema
from models import requires_login, requires_admin, DesignModel, ResultModel
from werkzeug.security import safe_str_cmp
from flask_uploads import UploadNotAllowed
from libs import image_helper
import os
import datetime
import logging
import traceback

logger = logging.getLogger()
webresult_all_blueprint = Blueprint('webresults_all', __name__)
result_schema = ResultSchema()
result_list_schema = ResultSchema(many=True)


@webresult_all_blueprint.route("/")
@requires_login
@requires_admin
def index():
    results = ResultModel.find_all()
    return render_template("results/indexall.html", results=result_list_schema.dump(results))


@webresult_all_blueprint.route("/download/<string:result_id>")
@requires_login
@requires_admin
def download_file(result_id):

    result = ResultModel.find_by_id(result_id)

    model = DesignModel.find_by_id(result.model_id)

    if model and   session["admin"] == True:
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'], os.path.dirname(result.objname))
            return send_from_directory(directory=uploads, filename=os.path.basename(result.objname),attachment_filename=result.name,as_attachment=True)
        except:
            traceback.print_exc()
            return "File not found!"
    else:
        flash('Unauthorized: Unable to download model id {}'.format(model_id), 'danger')

        return redirect(url_for(".index"))

@webresult_all_blueprint.route("/delete/<string:result_id>")
@requires_login
@requires_admin
def delete_result(result_id):
    result = ResultModel.find_by_id(result_id)
    model = DesignModel.find_by_id(result.model_id)
    if result and model and session["admin"] == True:
        result.delete_from_db()
        try:
            uploads = os.path.join( current_app.config['UPLOADED_FILES_DEST'])
            os.remove(os.path.join(uploads,result.objname))
        except:
            traceback.print_exc()
            flash('Result File deletion failed','danger')
    else:
        flash('Unauthorized: Unable to delete result id {}'.format(result_id), 'danger')

    return redirect(url_for(".index"))

modelapp/templates/results/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <header>
        <dl>
            <dt>
                <h1 aria-describedby="headerHelp" class="mb-0" ">Results</h1>
            </dt>
            <dd>
                <medium id="headerHelp" class="form-text text-muted mt-0">for model name ({{ model_name }})</medium>
            </dd>
        </dl>
    </header>
   
    <section>
        <div class="list-group mt-2">
            {% for result in results %}
            <div class="list-group-item" >
                
                    <dl>
                        <dt>
                            <a class="list-group-item-heading" style="font-size: 150%" aria-describedby="fileHelp" href="{{ url_for('webresults.download_file', result_id=result.id) }}" target="_blank">{{ result.name }}</a>
                        </dt>
                        <dd>
                            <small id="fileHelp" class="form-text text-muted">SavedBy: {{ result.saved_by }}, Date/Time: {{ result.time_created |strftime }}</small>
                        </dd>
                        <a class="btn btn-danger btn-sm mt-0" href="{{ url_for('webresults.delete_result', result_id=result.id) }}">
                            Permanently Delete Result
                        </a>
                    </dl>
            </div>
            {% endfor %}
        </div>


    </section>
</div>
{% endblock %}

modelapp/templates/results/indexall.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <header>
        <h1>All Results</h1>
    </header>
    <section>
        <div class="list-group">
            {% for result in results %}
            <div class="list-group-item" >
                
                <dl>
                    <dt>
                        <a class="list-group-item-heading" style="font-size: 150%" aria-describedby="fileHelp" href="{{ url_for('webresults_all.download_file', result_id=result.id) }}">{{ result.name }}</a>
                    </dt>
                    <dd>
                        <small id="fileHelp" class="form-text text-muted">SavedBy: {{ result.saved_by }}, Date/Time: {{ result.time_created |strftime }}, model-id: {{ result.model}} </small>
                    </dd>
                    <a class="btn btn-danger btn-sm mt-0" href="{{ url_for('webresults_all.delete_result', result_id=result.id) }}">
                        Permanently Delete Result
                    </a>
                </dl>
        </div>
            {% endfor %}
        </div>


    </section>
</div>
{% endblock %}